CREATE TABLE TB_MES (
  ID_MES INTEGER  NOT NULL   IDENTITY ,
  NOME VARCHAR(10)      ,
PRIMARY KEY(ID_MES));
GO




CREATE TABLE TB_MATRICULA (
  ID_MATRICULA INTEGER  NOT NULL   IDENTITY ,
  NOME VARCHAR(60)    ,
  SEXO CHAR(1) CHECK ( SEXO LIKE 'M' OR SEXO LIKE 'F')    ,
  DATA_NASCIMENTO DATE    ,
  TELEFONE VARCHAR(12)    ,
  CPF VARCHAR(14)    ,
  ENDERECO VARCHAR(100)    ,
  MAT_STATUS VARCHAR(10) CHECK (MAT_STATUS LIKE 'ATIVO' OR MAT_STATUS LIKE 'INATIVO')    ,
  PROBLEMA CHAR(1) CHECK ( PROBLEMA LIKE 'S' OR PROBLEMA LIKE 'N')    ,
  DESCRICAO_PRO VARCHAR(100)    ,
  VALOR NUMERIC(10,2)      ,
PRIMARY KEY(ID_MATRICULA));
GO




CREATE TABLE TB_ATIVIDADE (
  ID_ATIVIDADE INTEGER  NOT NULL   IDENTITY ,
  DESCRICAO VARCHAR(20)  NOT NULL    ,
PRIMARY KEY(ID_ATIVIDADE));
GO




CREATE TABLE TB_PAGAMENTO (
  ID_PAGAMENTO INTEGER  NOT NULL   IDENTITY ,
  ID_MES INTEGER  NOT NULL  ,
  ID_MATRICULA INTEGER  NOT NULL  ,
  VALOR NUMERIC(10,2)    ,
  DATA_PAGAMENTO DATE    ,
  ANO INTEGER      ,
PRIMARY KEY(ID_PAGAMENTO)    ,
  FOREIGN KEY(ID_MATRICULA)
    REFERENCES TB_MATRICULA(ID_MATRICULA),
  FOREIGN KEY(ID_MES)
    REFERENCES TB_MES(ID_MES));
GO


CREATE INDEX FK_TB_PAGAMENTO ON TB_PAGAMENTO (ID_MATRICULA);
GO
CREATE INDEX TB_PAGAMENTO_FKIndex2 ON TB_PAGAMENTO (ID_MES);
GO


CREATE INDEX IFK_MATRICULA_EFETUA_PAGAMENTO ON TB_PAGAMENTO (ID_MATRICULA);
GO
CREATE INDEX IFK_MES_DO_PAGAMENTO ON TB_PAGAMENTO (ID_MES);
GO


CREATE TABLE TB_MATRICULA_ATIVIDADE (
  ID_MATRICULA INTEGER  NOT NULL  ,
  ID_ATIVIDADE INTEGER  NOT NULL    ,
PRIMARY KEY(ID_MATRICULA, ID_ATIVIDADE)    ,
  FOREIGN KEY(ID_MATRICULA)
    REFERENCES TB_MATRICULA(ID_MATRICULA),
  FOREIGN KEY(ID_ATIVIDADE)
    REFERENCES TB_ATIVIDADE(ID_ATIVIDADE));
GO


CREATE INDEX FK_TB_MATRICULA_ATIVIDADE ON TB_MATRICULA_ATIVIDADE (ID_MATRICULA);
GO
CREATE INDEX FK2_TB_MATRICULA_ATIVIDADE ON TB_MATRICULA_ATIVIDADE (ID_ATIVIDADE);
GO


CREATE INDEX IFK_MATRICULA_PARA_ATIVIDADE ON TB_MATRICULA_ATIVIDADE (ID_MATRICULA);
GO
CREATE INDEX IFK_ATIVIDADE_PARA_MATRICULA ON TB_MATRICULA_ATIVIDADE (ID_ATIVIDADE);
GO



