CREATE TABLE TB_MATRICULA (
  ID_MATRICULA INTEGER  NOT NULL   IDENTITY ,
  NOME VARCHAR(60)    ,
  SEXO SET('M','F')    ,
  DATA_NASCIMENTO DATE    ,
  TELEFONE VARCHAR(12)    ,
  CPF VARCHAR(14)    ,
  ENDERECO VARCHAR(100)    ,
  ATIVIDADE SET('N', 'M', 'Y','H','D')    ,
  MAT_STATUS SET('ATIVO', 'INATIVO')    ,
  PROBLEMA SET('S','N')    ,
  DESCRICAO_PRO VARCHAR(100)      ,
PRIMARY KEY(ID_MATRICULA));
GO




CREATE TABLE TB_PAGAMENTO (
  ID_PAGAMENTO INTEGER  NOT NULL   IDENTITY ,
  ID_MATRICULA INTEGER  NOT NULL  ,
  VALOR NUMERIC(10,2)    ,
  DATA_PAGAMENTO DATE    ,
  ANO INTEGER    ,
  MES INTEGER      ,
PRIMARY KEY(ID_PAGAMENTO)  ,
  FOREIGN KEY(ID_MATRICULA)
    REFERENCES TB_MATRICULA(ID_MATRICULA));
GO


CREATE INDEX FK_TB_PAGAMENTO ON TB_PAGAMENTO (ID_MATRICULA);
GO


CREATE INDEX IFK_MATRICULA_EFETUA_PAGAMENTO ON TB_PAGAMENTO (ID_MATRICULA);
GO



